### ISSUE TITLE
onOffAllLights funktioniert nicht, wenn "Nur angeschaltete Lichter einer Gruppe schalten" aktiv ist

### ISSUE THREAD

**Issue by QuoxelNet** [iobroker-community-adapters/ioBroker.hue-extended#101]
Wenn man die Option "Nur angeschaltete Lichter einer Gruppe schalten" in den Einstellungen des Adapters aktiviert hat, bewirkt ein Setzen des Datenpunkts "onOffAllLights" einer Gruppe gar nichts - er schaltet weder an noch aus. Erwarten würde ich, dass dieser immer die ganze Gruppe schaltet, egal wie "Nur angeschaltete Lichter..." gesetzt ist, und dass der Datenpunkt "on" nur geschaltete Lichter beim Ausschalten berücksichtigt...
Ich habe die Option der geschalteten Lichter aktiv, sonst würde eine Änderung der Farbtemperatur sämtliche Lampen anschalten (auch die, die bewusst ausgelassen wurden).

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
