### ISSUE TITLE
hue to xy pro Lampe einstellbar

### ISSUE THREAD

**Issue by getriebesand** [iobroker-community-adapters/ioBroker.hue-extended#107]
Hallo, ist es eventuell möglich, pro Lampe einzustellen, ob sie hue oder xy nutzt?
Ich habe eine Lampe von MLI und sie nutzt hue, aber ich habe auch eine von Lidl, die nutzt xy.

manufacturename: MLI
modelid: ZBT-ExtendedColor

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
