### ISSUE TITLE
Datenpunkt für Link_quality

### ISSUE THREAD

**Issue by michipi85** [iobroker-community-adapters/ioBroker.hue-extended#109]
Ist es möglich ein weiteren Datenpunkt für die Signalstärke des Geräts hinzuzufügen.
Unter dem Zigbee Adapter habe ich einen Datenpunkt der nennt sich Link_quality. Ich möchte wissen wie gut oder schlecht die Verbindung der einzelnen Geräten mit Routern/Bridge ist, um vielleicht einen geeigneteren Standort zu finden oder ob ich wo nachbessern muss.

Vielen Dank.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
