### ISSUE TITLE
Change Connection Parameters to Hue Bridge

### ISSUE THREAD

**Issue by DeadlyVirez** [iobroker-community-adapters/ioBroker.hue-extended#112]
Following Error presents itself when trying to connect to my deCONZ container that has secure connection on port 8443 and not the standard port of 443.

is there a way to change this port for the connection via configuration?

`hue.0 | 2020-12-26 21:10:38.273 | error | (2381) connect ECONNREFUSED 192.168.0.101:443
hue.0 | 2020-12-26 21:10:38.272 | warn | (2381) could not connect to HUE bridge (192.168.0.101:443)
hue.0 | 2020-12-26 21:10:33.264 | error | (2381) connect ECONNREFUSED 192.168.0.101:443
hue.0 | 2020-12-26 21:10:33.263 | warn | (2381) could not connect to HUE bridge (192.168.0.101:443)`

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
