### ISSUE TITLE
deconz remote 10+ seconds latency 

### ISSUE THREAD

**Issue by handy80** [iobroker-community-adapters/ioBroker.hue-extended#114]
Hi,
i found an issue (more performance than bug) 
running two RPi's 
1. deconz + fhem
2. iobroker with hue-extended
- both are connected via ethernet cable to the same router/switch
- motion detectors are xiaomi/mijia/mi motion sensors with light sensor included
- iobroker is syncing fhem data where deconz-devices (incl. sensors) are included.
- using iobroker-smartcontrol to react on motion detections to switch on the light in my hall.

-> using in iobroker the fhem data points is switching under a second.
-> using in iobroker the hue-extended data point is switching inbetween 3-10+ seconds.

Is this performance to be known/expected? Can I tweak the performance?
Do you need more info to investigate here?

Please don't get me wrong, the adapter works like a charm and the data points are clear and well structured. It's just not usable with this latency for my use case.

Kind regards and happy new year :-)
Handy80

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
