### ISSUE TITLE
Logging optional 

### ISSUE THREAD

**Issue by testit2020** [iobroker-community-adapters/ioBroker.hue-extended#118]
For every Light it is an Log like: 

(1093) Attempt 1x - Successfully set

When it is possible, make it **optional in Instance settings** and when Logging do it with the actual State.

-> 

(1093) Attempt 1x - Successfully set **Light Schrank to true.**

Thank you.

**Comment by Zefau** [comment]
You may set the hue-extended instance to `warn` (instead of `info`) [ via expert view in the list of interfaces ]

**Comment by testit2020** [comment]
Thank you. It works for not getting info about switch process.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
