### ISSUE TITLE
Konfiguration von Lampengruppen nicht möglich

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.hue-extended#120]
Hi,
ich möchte die Gruppierung von Lampen dynamisch anpassen - es soll wenn jemand auf der Terrasse ist die Terrassenlampen in die Gruppe für die Klingelbenachichtigung aufaufgenommen werden. Dazu wollte ich in der Gruppe unter _commands den Befehl {"lights": ["3","6","7"]} absetzen. Dies funktioniert jedoch nicht.

Wenn ich nachfolgende Befehle per EXEC in Blockly ausführe funktioniert dies.

curl -X PUT --data '{"lights": ["3","6","7"]}' --url 192.168.178.100/api/xxxx/groups/8
curl -X PUT --data '{"lights": ["3"]}' --url 192.168.178.100/api/xxxx/groups/8

Im Debug-Log kommt nachfolgendes. Was mache ich falsch?

`
hue-extended.0 | 2021-01-18 09:55:00.944 | debug | (14956) Running Garbage Collector for hue-extended.0...
-- | -- | -- | --
hue-extended.0 | 2021-01-18 09:54:45.875 | debug | (14956) Successfully set /groups/8/action/on on Klingelbenachrichtigung (to true).
hue-extended.0 | 2021-01-18 09:54:45.875 | warn | (14956) Attempt 1x - Error setting /groups/8/action/lights: parameter, lights, not available
hue-extended.0 | 2021-01-18 09:54:45.853 | debug | (14956) Attempt 1x - Send commands to Klingelbenachrichtigung (groups/8/action): {"lights":["3","6","7"],"on":true}.
hue-extended.0 | 2021-01-18 09:54:45.853 | debug | (14956) sendCommand: {"path":"groups.008-klingelbenachrichtigung","type":"groups","name":"Klingelbenachrichtigung","uid":"8","trigger":"groups/8/action","commands":{"lights":["3","6","7"],"on":true}}
hue-extended.0 | 2021-01-18 09:54:44.865 | debug | (14956) Add to queue ({"path":"groups.008-klingelbenachrichtigung","type":"groups","name":"Klingelbenachrichtigung","uid":"8","trigger":"groups/8/action"}) commands: {"lights":["3","6","7"],"on":true
hue-extended.0 | 2021-01-18 09:54:44.864 | debug | (14956) State of hue-extended.0.groups.008-klingelbenachrichtigung.action._commands has changed {"val":"{\"lights\": [\"3\",\"6\",\"7\"]}","ack":false,"ts":1610960084860,"q":0,"from":"system.adapter.
hue-extended.0 | 2021-01-18 09:54:00.957 | info | (14956) Using polling for state updates.
hue-extended.0 | 2021-01-18 09:54:00.836 | info | (14956) Establishing secure connection to bridge..
hue-extended.0 | 2021-01-18 09:54:00.818 | info | (14956) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.hue-extended, node: v12.20.1, js-controller: 3.2.7
hue-extended.0 | 2021-01-18 09:54:00.637 | debug | (14956) statesDB connected
hue-extended.0 | 2021-01-18 09:54:00.637 | debug | (14956) States connected to redis: 127.0.0.1:9000
hue-extended.0 | 2021-01-18 09:54:00.585 | debug | (14956) States create User PubSub Client
hue-extended.0 | 2021-01-18 09:54:00.585 | debug | (14956) States create System PubSub Client
hue-extended.0 | 2021-01-18 09:54:00.580 | debug | (14956) Redis States: Use Redis connection: 127.0.0.1:9000
hue-extended.0 | 2021-01-18 09:54:00.579 | debug | (14956) objectDB connected
hue-extended.0 | 2021-01-18 09:54:00.576 | debug | (14956) Objects connected to redis: 127.0.0.1:9001
hue-extended.0 | 2021-01-18 09:54:00.565 | debug | (14956) Objects client initialize lua scripts
hue-extended.0 | 2021-01-18 09:54:00.565 | debug | (14956) Objects create User PubSub Client
hue-extended.0 | 2021-01-18 09:54:00.565 | debug | (14956) Objects create System PubSub Client
hue-extended.0 | 2021-01-18 09:54:00.513 | debug | (14956) Objects client ready ... initialize now
hue-extended.0 | 2021-01-18 09:54:00.480 | debug | (14956) Redis Objects: Use Redis connection: 127.0.0.1:9001
`

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
