### ISSUE TITLE
BWM presence data direkt pushen

### ISSUE THREAD

**Issue by testit2020** [iobroker-community-adapters/ioBroker.hue-extended#121]
Normalerweise werden die Daten in den Aktualisierungsintervall übertragen: Normal sind 10 Sekunden.

hue-extended.0.sensors.034-buero.state.presence

Frage kann man bei bestimmten Typen (Sensoren) insbesondere bei Bewegungsmeldern die Daten direkt an iobroker weitergeben unabhängig von dem Intervall?
Oder intern für diese BWM das interne Intervall runtersetzt auf 1s, so daß nur wenige Daten jede Sekunde übertragen werden?
Insbesondere "presence"-Status, aber vielleicht auch andere.

**Comment by ciddi89** [comment]
Hallo,

da ich auch gerne die BWM über ioBroker in Skripten nutzen möchte, habe ich mittlerweile einen indirekten Weg gefunden wie man die Presence Daten an ioBroker pushen kann. Ich weiß nicht ob es möglicherweise auch mit Android klappt. Da Hue aber diese Daten an HomeKit pusht habe ich mir virtuelle Schalter mit Yahka erstellt, diese werden von HomeKit bei Bewegung auf True und bei nicht Bewegung nach 10 sek. auf False gestellt. Das klappt bisher einwandfrei und ohne Verzögerung. Schöner wäre natürlich eine Lösung ohne Umwege. Aber ich denke da können wir noch lange drauf warten. 

Vielleicht hilft das den ein oder anderen weiter.

**Comment by Gurkoel** [comment]
Ich hab ein ähnliches Problem. Da ich Android-User bin kommt für mich eine Lösung über Homekit auch nicht in frage. Es wäre wirklich cool wenn dazu entwas kommen würde :).

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
