### ISSUE TITLE
JS-Controller 3.2.X

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hue-extended#123]
2021-01-20 20:27:57.194 - warn: hue-extended.0 (2340) State "hue-extended.0.scenes.HueLabsScenes.candlelight_romance.action.status" has no existing object, this might lead to an error in future versions

**Comment by darkman242** [comment]
hue-extended.0 | 2021-01-24 19:06:06.111 | warn | (28799) State "hue-extended.0.scenes.006-tv-bereich__wz_.fernsehen.action.scene" has no existing object, this might lead to an error in future versions

**Comment by Baenker** [comment]
Bei mir nach update js-controller ebenfalls:

`

  |   |   |  
-- | -- | -- | --
hue-extended.0 | 2021-03-13 08:09:29.079 | warn | (1255) State "hue-extended.0.scenes.003-hue_flur.bewegung_mittel.action.scene" has no existing object, this might lead to an error in future versions

`

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
