### ISSUE TITLE
[Feature] implement mac address into the object native store

### ISSUE THREAD

**Issue by sgc-fireball** [iobroker-community-adapters/ioBroker.hue-extended#127]
Hi,
it would be great, if the mac address of an lamp in the obj.native store.

Reason:
If a person rename the lamp the object id would be change. So no other custom scripts or other adapters that reference to these lamp can't work anymore.
These behaviour can fixed if the mac address are stores in the object native store or the mac address would be used as object id instand of NNN-lamp-name.

**Comment by Baenker** [comment]
please don´t use the mac-adress. Nobody knows the mac of the lamp. Don´t rename the name of the lamp. I have no Problems.... If i change the name. i change the script. No Problem and only 2 Minutes time...

**Comment by realPilotfish** [comment]
I would really love that.
This is the only data point that allows for a proper identification, no matter how names or iobroker ids might change.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
