### ISSUE TITLE
Weitere Integration von Deconz?

### ISSUE THREAD

**Issue by easybeat** [iobroker-community-adapters/ioBroker.hue-extended#129]
Hallo zusammen

plant ihr noch Verbesserungen/Erweiterungen bei der Integration von Deconz?

Danke und Gruss

**Comment by Zefau** [comment]
Nein. An was denkst du?

**Comment by easybeat** [comment]
Es gibt doch noch einige Fehler:
- in einigen Gruppen fehlen Szenen

![Screenshot 2021-02-09 163925](https://user-images.githubusercontent.com/37217887/107387827-7f49b200-6af5-11eb-8483-4cc662c30625.png)
![Screenshot 2021-02-09 163902](https://user-images.githubusercontent.com/37217887/107387834-7fe24880-6af5-11eb-9fd2-0de51fe82f71.png)

- bei TRV/Radiator Ventilen fehlt der Heatsetpoint

![Screenshot 2021-02-09 164002](https://user-images.githubusercontent.com/37217887/107387909-912b5500-6af5-11eb-9673-b3ae609b1ccc.png)

und wahrscheinlich gibts noch mehr...

Es wäre toll wenns eine Alternative zum Deconz Adapter geben würde.

Danke und Gruss
