### ISSUE TITLE
warnings due to wrong types in js-controller 3.3

### ISSUE THREAD

**Issue by EdgarM73** [iobroker-community-adapters/ioBroker.hue-extended#148]
Hi,

with the new js-controller there are at least two warnings in the log due to wrong datatypes 👍 
regards
E

`

hue-extended.1 | 2021-04-30 13:27:07.413 | warn | State value to set for "hue-extended.1.sensors.003-window_esszimmer.state.lux" has wrong type "number" but has to be "string"
-- | -- | -- | --
hue-extended.1 | 2021-04-30 13:27:07.413 | warn | State value to set for "hue-extended.1.sensors.003-window_esszimmer.state.lightlevel" has wrong type "number" but has to be "string"

`

**Comment by ppb1308** [comment]
Same issues here. MEssages like:
State value to set for "hue-extended.0.resourcelinks.peter_sensor_dg.classid" has to be type "string" but received type "number"

**Comment by jsuelwald** [comment]
![image](https://user-images.githubusercontent.com/2499585/123541497-395c5600-d745-11eb-9050-07d77db5a9a2.png)

Same here
