### ISSUE TITLE
Schaltbefehle gehen nicht an Geräte

### ISSUE THREAD

**Issue by amarony** [iobroker-community-adapters/ioBroker.hue-extended#149]
Ich habe aktuell die Version 2.0.1 installiert und leider kann ich keine Schaltbefehle senden.
Betroffen sind LEDVANCE Smart+ Steckdosen und Hue Lampen / Leuchten.
Ich nutze einen Conbee2.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
