### ISSUE TITLE
Adapter muss regelmäßig neugestartet werden, Problem mit Sensoren

### ISSUE THREAD

**Issue by Elonil** [iobroker-community-adapters/ioBroker.hue-extended#161]
Hallo!
Ich habe derzeit das Problem, dass ich den Adapter mehrfach pro Woche neustarten muss, da dieser in bestimmten Fällen nicht mehr reagiert auf meine Philips Hue Taster. Wenn ich die Taste drücke wird kein Event ausgelöst. Erst nach Neustart des Adapters werden die Events erkannt.

Wie kann ich das Problem lösen? Ich weiß aktuell nicht woher das Problem kommt, da ich es nicht lokalisieren kann.

Beste Grüße
Elonil

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
