### ISSUE TITLE
value.split(',') is not a function

### ISSUE THREAD

**Issue by Pheromir** [iobroker-community-adapters/ioBroker.hue-extended#164]
Hey,
when trying to set a hex or rgb value for my light group, the adapter crashes.

Error log:

host.phoscon | 2021-06-14 16:36:34.294 | error | instance system.adapter.hue-extended.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
hue-extended.0 | 2021-06-14 16:36:33.718 | warn | (26417) Terminated (UNCAUGHT_EXCEPTION): Without reason
hue-extended.0 | 2021-06-14 16:36:33.716 | info | (26417) terminating
hue-extended.0 | 2021-06-14 16:36:33.714 | info | (26417) Adapter stopped und unloaded.
hue-extended.0 | 2021-06-14 16:36:33.696 | error | (26417) value.split is not a function
hue-extended.0 | 2021-06-14 16:36:33.695 | error | at processImmediate (internal/timers.js:461:21)
hue-extended.0 | 2021-06-14 16:36:33.695 | error | at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5559:38)
hue-extended.0 | 2021-06-14 16:36:33.695 | error | at Adapter.emit (events.js:314:20)
hue-extended.0 | 2021-06-14 16:36:33.695 | error | at Adapter.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.hue-extended/hue-extended.js:366:32)
hue-extended.0 | 2021-06-14 16:36:33.695 | error | (26417) TypeError: value.split is not a function
hue-extended.0 | 2021-06-14 16:36:33.689 | error | (26417) uncaught exception: value.split is not a function

a very quick and dirty fix that seemed to work for me, was changing [Line 349](https://github.com/Zefau/ioBroker.hue-extended/blob/master/hue-extended.js#L349) from
`let value = commands[action];` to `let value = commands[action] + '';`

**Comment by trevon88** [comment]
Hi, i have the same trouble but only with the philips light stripe. Something is diffrent on this device....
Your fix wasn't working for me....

**Comment by trevon88** [comment]
Someone any Idea? 
I will do what i can to help....

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
