### ISSUE TITLE
Gewählte Szene von Gruppe hue-extended.0.groups.*.action.scene Feld leert sich.

### ISSUE THREAD

**Issue by suspect80** [iobroker-community-adapters/ioBroker.hue-extended#165]
Super Adapter!!

Gibt es eine Möglichkeit die zuvor gewählte Szene dauerhaft zu merken? Wenn man mit hue-extended.0.groups.*.action.scene eine Szene setzt verschwindet sie nach kurzer Zeit. Cool wäre es wenn dort die Szene solange sichtbar bleibt solange keine anderen Veränderungen an der Gruppe passiert sind. 

Vielen Dank

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
