### ISSUE TITLE
Motion Sensor "On" ist RO

### ISSUE THREAD

**Issue by Maaa90** [iobroker-community-adapters/ioBroker.hue-extended#170]
Die Motion Sensoren lassen sich über "On" - Wert "false" nicht mehr über ioBroker ausschalten, als wäre der Datenpunkt nur noch RO.
Triggert man in der Hue-App geht der Wert auf false und der Sensor schaltet keine Lichter.
![Bildschirmfoto 2021-07-18 um 23 17 59](https://user-images.githubusercontent.com/82117693/126082503-18804e39-54b3-4e37-aa7b-a07d30fc101b.png)

**Comment by rgnader** [comment]
Hab das selbe Problem!  Mit dem alten Hue Adapter ist das Problem nicht.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
