### ISSUE TITLE
_commands action does not accept hex value for hue light stripe

### ISSUE THREAD

**Issue by rarnken** [iobroker-community-adapters/ioBroker.hue-extended#174]
Trying to set the color of a hue light stripe with _commands action. The json is defined as following:

```json
{"on": true,"level": 50,"hex": "#0000FF", "transitiontime": 2}
```

The error message states that parameter hex is not available

`Attempt 1x - Error setting /lights/58/state/hex: parameter, hex, not available`

Tried it with v2.0.0 and v2.0.1

On a hue e14 this seems to be working. Do I miss something?

**Comment by deMarvin** [comment]
I have encountered the same problem, but only sometimes. Sometimes it works and sometimes it doesn't.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
