### ISSUE TITLE
has to be type "string" but received type "number" 

### ISSUE THREAD

**Issue by Kirdan62** [iobroker-community-adapters/ioBroker.hue-extended#177]
Bekomme folgende Meldung, obwohl ich den Objektbaum gelöscht und neu angelegt habe.

`

hue-extended.0 | 2021-08-15 10:21:46.418 | info | State  value to set for  "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be  type "string" but received type "boolean"
-- | -- | -- | --
hue-extended.0 | 2021-08-15 10:21:46.418 | info | State  value to set for  "hue-extended.0.sensors.203-flur_hue_bwm_1.state.presence" has to be  type "string" but received type "boolean"
hue-extended.0 | 2021-08-15 10:21:46.417 | info | State  value to set for  "hue-extended.0.sensors.073-haustür_bwm_outdoor.state.presence" has to  be type "string" but received type "boolean"
hue-extended.0 | 2021-08-15 10:20:45.688 | info | State  value to set for  "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has  to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:20:45.685 | info | State  value to set for  "hue-extended.0.sensors.221-hue_outdoor_light_sensor_2.state.lightlevel"  has to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:20:45.680 | info | State  value to set for  "hue-extended.0.sensors.204-hue_ambient_light_sensor_6.state.lightlevel"  has to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:20:45.679 | info | State  value to set for  "hue-extended.0.sensors.054-hue_ambient_light_sensor_5.state.lightlevel"  has to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:19:14.948 | info | State  value to set for  "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max"  has to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:19:14.948 | info | State  value to set for  "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min"  has to be type "string" but received type "number"
hue-extended.0 | 2021-08-15 10:19:14.947 | info | State  value to set for  "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has  to be type "string" but received type "number

`

**Comment by syscrash13** [comment]
Hey hab ein ähnliches Problem =)
hast du das auch erst seit der Admin 5 Umstellung?
Ich hab gestern mein System komplett neu aufgesetzt, aber der Fehler... bzw. die Info ist geblieben.

![Screenshot_2021-08-18-15-42-51-101_com android chrome](https://user-images.githubusercontent.com/82909963/129909102-5c34a1dc-7847-4301-baf0-c39e2725a09d.png)

**Comment by valbuz** [comment]
Hier dasselbe.
Seit Update auf Admin5

Bitte um Hilfe.
Danke

**Comment by syscrash13** [comment]
Hab etwas weiter gesucht und bin auf das Problem gestoßen, dass es mit js-controller 3.3.x zu tun hat und die Adapter angepasst werden müssen. Hier der Beitrag im deutschsprachigen Forum: https://forum.iobroker.net/topic/44624/js-controller-3-3-jetzt-im-latest/26

**Comment by valbuz** [comment]
Ja dies ist bekannt.
Hoffe dem Entwickler auch….?

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
