### ISSUE TITLE
Hue-extended sendet falschen Datentyp

### ISSUE THREAD

**Issue by bz7i** [iobroker-community-adapters/ioBroker.hue-extended#179]
ich bekomme seid einiger Zeit vom Hue-extended Adapter die Meldung das der Datentyp falsch ist.
Wie stell Ich das ab ?

<html>
<body>

hue-extended.0 | 2021-09-12 09:51:47.126 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
-- | -- | -- | --
hue-extended.0 | 2021-09-12 09:51:47.124 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:51:46.940 | info | State value to set for "hue-extended.0.sensors.052-hue_ambient_light_sensor_1.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:51:46.938 | info | State value to set for "hue-extended.0.sensors.003-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"

</body>
</html>

**Comment by MilaMops** [comment]
Hallo
Der Philips Hue-extended Adapter sendet bei mir nur bei zwei neuen Philips Hue Bewegungsmeldern einige falsche Datentypen.
Es handelt sich dabei um den philips hue Motion sensor, Model 929003067501
Das ist die neuere Version mit 7 Meter Reichweite.
Hier ein Ausschnitt aus dem Log:

![Log](https://user-images.githubusercontent.com/99895245/154518792-82c0db6e-87dc-4d6a-9b4a-489b9669f599.JPG)

Es werden nur 3 Datentypen fehlerhaft übermittelt:
-light_sensor_<Nr>.state.lightlevel
-light_sensor_<Nr>.state.dark
-motion_sensor_<Nr>.state.presence

Ich habe testweise den Philips Hue-Bridge Adapter verwendet. Dort werden die Datentypen korrekt übermittelt.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
