### ISSUE TITLE
HUE Bridge Warnung nach Außerbetriebnahme

### ISSUE THREAD

**Issue by nukleuz80** [iobroker-community-adapters/ioBroker.hue-extended#181]
Hi zusammen,

wie bekomme ich diese Meldung in den Logs weg?
Ich habe mich von der HUE-Bridge getrennt und nutze nur noch DeConz.

<html>
<body>

hue-extended.0 | 2021-10-28 15:07:17.918 | warn | Error connecting to Hue Bridge: Incorrect data return from Hue API. Already retried 1780x so far. Try again in 1 minute..
-- | -- | -- | --

</body>
</html>

Danke für Info.

**Comment by nukleuz80** [comment]
Ich möchte ausschliesslich den Adapter nutzen um Lichter und Sensoren von deConz zu erhalten, doch leider scheint das nicht möglich. Auch nach einer Neuinstallation des Adapters/Instanz und Neuanlage des Benutzer in Verbindung mit Phoscon (API Key), werden immer noch keine Lichter und Sensoren synchronisiert.

**Comment by Machinimo** [comment]
Das Problem ist bekannt und wurde bereits behoben, siehe #180 
Leider wurde bisher keine neue Version auf NPM veröffentlicht. Abhilfe schafft da nur ein Downgrade des DeConz-Package auf v2.12.6, zumindest ist das die Version, die ich bei mir im Einsatz habe und die ohne Fehler läuft.
Der hier erstellte Issue kann daher geschlossen werden.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
