### ISSUE TITLE
Sync mit Spotify und dynamische Szenen

### ISSUE THREAD

**Issue by djmarc75** [iobroker-community-adapters/ioBroker.hue-extended#182]
Hellole,
erstmal danke für den geilen Adapter.
Ist es machbar die Funktion "Sync mit Spotify" und die (neuen) dynamischen Szenen zu integrieren ?
Lässt sich ja momentan nur per APP schalten.
Viele Grüße
Der Marc

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
