### ISSUE TITLE
Moved to iobroker-community-adapters/ioBroker.hue-extended

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.hue-extended#183]
@Apollon77 I moved the repository to iobroker-community-adapters/ioBroker.hue-extended. Is there anything else to do? I'm sorry, for the direct ping, but since this is not a daily business I'm unsure of all tasks.

- [ ] update latest and stable repo with correct Github URL (is this required? @Apollon77, can you do this?)
- [ ] npm ownership to iobroker-community-adapters (by @Zefau)

**Comment by Jey-Cee** [comment]
Hi Zefau,
we have a step by step manual for this: https://github.com/iobroker-community-adapters/info#add-git-repo-to-organization

> [ ] update latest and stable repo with correct Github URL (is this required? @Apollon77, can you do this?)
Yes it is required. Please do this by yourself as @Apollon77 is always bussy.

Greets 
Jey Cee

**Comment by Apollon77** [comment]
I did it now
