### ISSUE TITLE
Display error at instance configuration

### ISSUE THREAD

**Issue by MetathronZ** [iobroker-community-adapters/ioBroker.hue-extended#191]
Hello,

I setup a new iobroker installation on a new installed Rapberry Pi 3. Everything was up to date.
I use a docker installation with macvlan network adapter. 
I bind the ports 8081 from container to host.
The image I use is buanet/iobroker:latest-v6
The first configuration of Admin works fine, and the discovery of the adapters finds all my environment.
Now I want to configute my Hue bridge connection via Philipps Hue extended Adapter, but on the configuration page I only see this:
![grafik](https://user-images.githubusercontent.com/99765894/154846534-55fce5be-ffad-46a8-b046-face5d4a5d35.png)

In the log is now error entry.
What can I do?

Thnaks for your help
Thorsten

**Comment by Zefau** [comment]
This is an error with dark mode. Switch to normal / white mode temporarily.

**Comment by MetathronZ** [comment]
Thanks, this help.

Issue closed
