### ISSUE TITLE
Falsche Datentypen

### ISSUE THREAD

**Issue by BenAhrdt** [iobroker-community-adapters/ioBroker.hue-extended#209]
Es gibt haufenweise falsche Datentypen:
Adapter Version 2.0.0

![image](https://user-images.githubusercontent.com/92173565/165583926-fa1f7ff0-113b-467a-9174-434993229f2f.png)

**Comment by Phantomkommander** [comment]
Dem möchte ich mich gerne anschließen

`<html>
<body>


hue-extended.0 | 2022-06-29 18:25:31.674 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
-- | -- | -- | --
hue-extended.0 | 2022-06-29 18:25:31.670 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:23:00.484 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:23:00.482 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:20:29.291 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:20:29.289 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:17:58.166 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 18:17:58.164 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:12:55.856 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:12:55.854 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:10:55.098 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:10:55.097 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:07:53.801 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:07:53.800 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:05:52.871 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:05:52.870 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:02:51.607 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 17:02:51.605 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:57:49.243 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:57:49.242 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:55:48.249 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:55:48.247 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:48:14.964 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:48:14.921 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:45:43.891 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:45:43.889 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:43:12.799 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:43:12.798 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:38:10.381 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:38:10.379 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:35:39.196 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:35:39.194 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:33:08.255 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:33:08.254 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:28:05.960 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 16:28:05.959 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:36:10.484 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:36:10.483 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:33:09.115 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:33:09.114 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:31:08.304 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:31:08.258 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:28:06.741 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:28:06.740 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:26:05.893 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:26:05.845 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:23:04.430 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:23:04.428 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:21:03.554 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:21:03.551 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:18:32.356 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:18:32.355 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:16:01.279 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:16:01.278 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:13:30.039 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:13:30.038 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:10:58.743 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:10:58.742 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:08:27.536 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 15:08:27.535 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:05:56.504 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:05:56.455 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:03:25.290 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:03:25.288 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:00:54.281 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 14:00:54.276 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:58:23.183 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:58:23.181 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:55:52.073 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:55:52.071 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:53:20.856 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:53:20.851 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:50:49.825 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:50:49.823 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:48:48.857 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:48:18.596 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:48:18.594 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:48:18.591 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:44:16.538 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:44:16.537 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:44:16.536 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:44:16.535 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.daylight_any" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:44:16.533 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.dark_all" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:43:39.008 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:43:39.007 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:43:39.007 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.daylight_any" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:43:39.005 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.dark_all" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:40:53.062 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:40:53.061 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:38:36.596 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:38:36.595 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:36:05.452 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:36:05.449 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:33:34.317 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:33:34.315 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:31:33.486 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:31:03.315 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:31:03.315 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:31:03.314 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.dark" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:31:03.271 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:30:33.032 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:30:02.751 | info | State value to set for "hue-extended.0.groups.000-all_lights.presence.state.presence" has to be type "string" but received type "boolean"
hue-extended.0 | 2022-06-29 13:28:32.133 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2022-06-29 13:28:32.132 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"


</body>
</html>`

**Comment by Bibo13** [comment]
Gibt es in diesem Fall noch Service im Adapter? Oder ist er tot und wir sollten uns einen anderen installieren?

**Comment by valbuz** [comment]
Gibt's schon Neues?
Was habt ihr für eine Lösung gesucht/gefunden?

Danke
Pat

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
