### ISSUE TITLE
Scene startet nicht (bei deConz-Bridge)

### ISSUE THREAD

**Issue by JayJay68** [iobroker-community-adapters/ioBroker.hue-extended#216]
Wenn ich bei einer Gruppe bei "action.scene" die ID einer Scene setze, startet die Scene nicht.
Laut ioBroker-Log wird das Kommando   (groups/24/action): {"scene":"2","on":true}    ausgeführt.

Dies mag bei normalen HUE-Bridges so funktionieren, leider aber nicht bei den deConz-Bridges (Conbee, Raspbee,...). Hier muss laut REST-API (https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/scenes/#recall-scene) dieser Befehl ausgeführt werden:

`PUT /api/<apikey>/groups/<group_id>/scenes/<scene_id>/recall`

Bei der Beschreibung für ...groups/<group-id>/action  kann man laut o.g. REST-API-Doku keine Szenen triggern.

Ansonsten: VIELEN DANK für den tollen Adapter! Endlich kann ich meine Lampen zuverlässig steuern. Insbesondere kann ich nun endlichen in meiner Jarvis-Visualisierung Widgets hinzufügen, um die Farben zu ändern (mit Datenpunkt .hex). Das hat mit dem deConz-Adapter einfach nicht funktionieren wollen.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
