### ISSUE TITLE
Probleme mit Conbee Stick

### ISSUE THREAD

**Issue by X-Renegade-X** [iobroker-community-adapters/ioBroker.hue-extended#259]
Mahlzeit,

das System lief bei mir jetzt knapp 2 Jahre einwandfrei. Seit gestern jedoch habe ich urplötzlich einen Fehler drauf. Es lässt sich nichts mehr steuern.

`hue-extended.0 | 7064 | 2023-01-08 09:59:30.570 | warn | Error connecting to Hue Bridge: Incorrect data return from Hue API. Already retried 10x so far. Try again in 1 minute..`

Ich habe den Adapter neu gestartet, den ganzen Host, den Stick und auch alle Updates im ioBroker sowie am Stick durchgeführt.
Der Fehler bleibt.
Über die IP ist der Stick allerdings einwandfrei erreichbar und auch alle Lichter steuerbar.

Die Einstellungen des Adapters wurden nicht verändert. Allerdings habe ich auch einen neuen Benutzer angefordert.
Hat auch nichts gebracht.

Was kann ich noch machen?

mfG
Rene

**Comment by ingo-k** [comment]
Ich habe alles in Docker-Containern laufen und eben mal versucht auf das "neue" Image deconzcommunity/deconz zu wechseln (Asche auf mein Haupt, dass ich seit nem Jahr nicht mehr geschaut habe...). Habe dort alle möglichen Gateway-Versionen versucht, aber keine hat funktioniert - immer da oben beschriebene Problem.
Das letzte, was bei mir funktioniert, ist das Image marthoc/deconz:stable (Gateway in Version 2.12.06) - darauf bin ich jetzt wieder umgestiegen.
Der deconz-Adapter läuft auch mit dem neuen Image und kriegt nen connect zum Gateway, daher vermute ich dass es am hue-extended-Adapter liegt...

Hat jemand ne Idee? Würde mich auch als Tester zur Verfügung stellen ;-)
Beste Grüße,
Ingo

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
