### ISSUE TITLE
v2.0.1 Admin 6.3.5 Keine sichtbaren Elemente

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.hue-extended#263]
![image](https://user-images.githubusercontent.com/84818934/213799397-566ca969-3832-4a6c-94fb-0ee74b5e9131.png)

**Comment by MS511** [comment]
Es ist möglicherweise nur eine falsche Schrift-/Hintergrundfarbe. Versucht man mit der Maus Bereiche festzuhalten und zu ziehen (so wie man Text markieren würde), wird an manchen Stellen Text sichtbar.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
