### ISSUE TITLE
Include rotation wheel from HUE tap dial switch

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.hue-extended#276]
I use the the hue_push_client script from:
https://forum.iobroker.net/topic/47391/hue-push-api-f%C3%BCr-hue-adapter

And if I rotait the wheel I get folloring message:

"owner":{"rid":"xxx","rtype":"device"},"relative rotary":{"last event":{"action":"start","rotation":{"direction":"counterclockwise","duration":400,"steps":15}}}}

Is it possible to include the wheel into the adapter?

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
