### ISSUE TITLE
where to set adapter.config.maxAttempts 

### ISSUE THREAD

**Issue by seb2010** [iobroker-community-adapters/ioBroker.hue-extended#86]
Hello,
I saw the ability if the adapter to retry sendCommand-attempts if the device is unreachable. This is done up to MAX_ATTEMPS times. this value may be overwritten by the adapter.config.maxAttempts variable. But where can I set this variable in the adapter-config-pane?
My scenraio is, that I have some unstable connections to some lights. When I use a script to emulate activity for a vacation absence, it is very bad to have some switching commands not to come through. I need the adapter to retry the sendCommand indefinitely until the device is reachable and the commands went through.
So my hope is to set the adapter.config.maxAttempts variable somewhere to a very high number to reach this behaviour. Where can this be found? Or is this feature possible to be implemented (resulting in indefinite retries)?
Cheers
Sebastian

**Comment by Zefau** [comment]
It is simply not implement in the adapter configuration interface. I can provide this though.

**Comment by seb2010** [comment]
Hi @Zefau, this would be really great and much appreciated. I think overall, this improves switching reliability.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
