### ISSUE TITLE
szene wird nicht richtig einsortiert

### ISSUE THREAD

**Issue by Timmes123** [iobroker-community-adapters/ioBroker.hue-extended#97]
Hey @Zefau, ich wusste gar nicht, dass der adapter auch von dir ist :-)
du machst echt nen guten Job.
Auf dein anraten hin hab ich ihn trotzdem wieder installiert und direkt nen Fehler in verbindung mit deconz entdeckt
Ich hab Szenen bisher nur in eine Gruppe eingerichtet und immer die erste Szene wird wie hier gezeigt falsch einsortiert.
Hab die auch schon in deconz gelöscht, dann wird eben die nächste szene falsch einsortiert.

![image](https://user-images.githubusercontent.com/73311538/99003327-373ee180-253e-11eb-81c2-813fa7dd0663.png)

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
