### ISSUE TITLE
Button "Adapterwebsite öffnen" in Instanzliste funktioniert nicht mit Deconz

### ISSUE THREAD

**Issue by Timmes123** [iobroker-community-adapters/ioBroker.hue-extended#98]
du rufst auf : https://IP/debug/clip.html
richtig wäre aber http://IP

ich hoffe ich nerve dich nicht mit meinen vielen issues^^

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
