### ISSUE TITLE
Falscher bri Wert bei command

### ISSUE THREAD

**Issue by japapu** [iobroker-community-adapters/ioBroker.hue-extended#99]
Hi,

wenn ich versuche, meine Light groups mit commands anzusprechen und sich hierbei nur "on" ändert, alle anderen Werte jedoch so bleiben, dann werden nicht die richtigen Werte an die Lampen gesendet.

**Beispiel:**

Nehmen wir an, die Werte sind folgendermaßen gesetzt:
on: true
hue: 260
bri: 254
sat: 254
alert: none
transitiontime: 3

Ich sende folgenden Command: {"on":false,"alert":"none","transitiontime":3}
Wie erwartet, gehen die Lampen aus.

Nun sende ich anschließend folgenden Command: {"hue":260,"bri":254,"sat":254,"alert":"none","transitiontime":3}
Entgegen meiner Erwartung schalten sich die Lampen nun nicht mit bri 254, sondern mit bri 1 an.

Es scheint also, wenn sich nur der Parameter "on" ändert und alle anderen Werte gleich bleiben, dann wird bri zB ignoriert und default 1 gesetzt?

Gruß Jan

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
